#

include:
  - /.gitlab-ci/extends.yml
  - /.gitlab-ci/variables.yml
  #
  - /.gitlab-ci/stages/prepare.yml
  - /.gitlab-ci/stages/quality.yml
  - /.gitlab-ci/stages/register.yml
  - /.gitlab-ci/stages/deploy.yml
  - /.gitlab-ci/stages/notify.yml

#

stages:
  - "Prepare"
  - "Build"
  - "Code Quality"
  - "Register Docker Image"
  - "Test Docker Image"
  - "Deploy Standup"
  - "Send Url to GitHub"
  - "Make a new release"
  - "Deploy Standup to prod"
