---
dist: xenial
language: node_js
git:
  depth: 5
node_js: stable
cache: yarn

before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash
  - export PATH="$HOME/.yarn/bin:$PATH"

install:
  - yarn --frozen-lockfile

script:
  - yarn build
  - yarn lint
  - yarn test

before_deploy:
  - git config user.name "Social Groovy Bot"
  - git config user.email "45039513+SocialGroovyBot@users.noreply.github.com"

deploy:
  github-token: "$GITHUB_TOKEN"
  keep-history: true
  local_dir: build
  provider: pages
  skip_cleanup: true
  target-branch: gh-pages
  on:
    branch: master

env:
  global:
    - PUBLIC_URL="/standup/"
    - secure: H4J7TcwXXbgHT957dv9abdc5N1Ir6jfAJaIlCV7feYCfqweBLOAEhveQuDBTNdX3Fxqv50PUWbOY4/e/TQ49Pvqy3IiEZsq0L/Ry35nKVKK76oYLUJdR4OWJiUPt7CoNYfgl0SYGoJ3ywrOrqCA0z1WjEuXHHb/hI/9rU89fEPuTPLC5CWallcxd8nH0RSgfE1ES6ghoGPeVTzWhgkA8aaKjtSs4axDTcpsHoRipMNlMe5dJ6QlzOAvKUmFXayumAEow+vhhGNnfeiA/7jKFZVS3hxN5ycNtnlBcEKgA9PG780uTvHQca8cCUW9WUUdDi/CAmh3SzzK3XQTuGLYjL86e27XrGtX4A+LvirXEJjcpywag/b++ccgK6VNOtFWtVeuUIzcAgV8WQ4Uz3U9nQxj8rTmg8La77HvUV1vUQ4TKZ+bD3I9u7HGnfUmQrEQ99HS0cMdD78e0m4AfE5jWTfzJj8sRWTMhJqhQQQ5W0eEan/yAbiYeMyAvzZC0nU/hgWto7mvYA80a4WsBji05IdnGlSEzpN41K9TQjHWlyLqeO842fOrOY+BPrkWofA8DAcqzFGc+VlNe6sonOb7HS5pJxenSczvwRhLtrcetam77s6cmR4/lF8YisD3f6EZwtGRE0bMBtZ8IZMAgQZaw10UtkYKerZC6s11u9/2KL1g=
