.base_node_stage:
  image: node:10
  before_script:
    - curl -o- -L https://yarnpkg.com/install.sh | bash
    - export PATH="$HOME/.yarn/bin:$PATH"
    - yarn --frozen-lockfile

.base_register_to_gitlab_stage:
  image: docker:${DOCKER_VERSION}
  services:
    - docker:${DOCKER_VERSION}-dind
  before_script:
    - echo "${CI_JOB_TOKEN}" | docker login ${CI_REGISTRY} -u gitlab-ci-token --password-stdin
  script:
    - >
      if [[ -n "${CI_COMMIT_TAG}" ]]; then
        export TAG=$(printf "${CI_COMMIT_TAG}" | sed "s/^v//")
      else
        export TAG=${CI_COMMIT_REF_SLUG}
      fi
    #
    - docker pull ${IMAGE_NAME}:${CI_COMMIT_BEFORE_SHA} || true
    - docker pull ${IMAGE_NAME}:${TAG} || true
    - docker pull ${IMAGE_NAME}:master || true
    - echo "> docker build ${DOCKER_BUILD_ARGS} --cache-from ${IMAGE_NAME}:${CI_COMMIT_BEFORE_SHA} --cache-from ${IMAGE_NAME}:${TAG} --cache-from ${IMAGE_NAME}:master -t ${IMAGE_NAME}:${CI_COMMIT_SHA} -t ${IMAGE_NAME}:${TAG} ${CONTEXT}"
    - docker build ${DOCKER_BUILD_ARGS}
        --cache-from ${IMAGE_NAME}:${CI_COMMIT_BEFORE_SHA}
        --cache-from ${IMAGE_NAME}:${TAG}
        --cache-from ${IMAGE_NAME}:master
        -t ${IMAGE_NAME}:${TAG}
        -t ${IMAGE_NAME}:${CI_COMMIT_SHA}
        ${CONTEXT}
    - docker push ${IMAGE_NAME}:${CI_COMMIT_SHA}
    - docker push ${IMAGE_NAME}:${TAG}
