variables:
  DOCKER_DRIVER: overlay2
  DOCKER_HOST: tcp://localhost:2375
  IMAGE_INFRA_BASE_NAME: "infra/images-docker"
  NGINX_VERSION: "1.17"
  INFRA_GIT_DEPLOY_VERSION: "1.0"
  INFRA_GIT_TAG_RELEASE_VERSION: "1.0"
  INFRA_HELM_VERSION: "1.0"
  INFRA_CURL_VERSION: "1.0"
  FRONT_PORT: 80
  CLUSTER_NAME: "dev"
  APP_NAME: "standup"
  FEATURE_ENVIRONMENT_NAME: "feature"
  MASTER_ENVIRONMENT_NAME: "master"
  PREPROD_ENVIRONMENT_NAME: "prep"
  PROD_ENVIRONMENT_NAME: "prod"
