.deploy_standup_k8s: &deploy_stand_up
  image:
    name: $CI_REGISTRY/$IMAGE_INFRA_BASE_NAME/docker-kube:latest
    entrypoint: [""]
  allow_failure: false

.deploy-standup-k8s-feature:
  <<: *deploy_stand_up
  before_script:
  - HASH_BRANCH_NAME=$(printf "$CI_COMMIT_REF_NAME" | sha1sum | cut -c1-5)
  - export HASH_BRANCH_INGRESS=$HASH_BRANCH_NAME
  - export HASH_BRANCH_NAME=-$HASH_BRANCH_NAME
  - envsubst < k8s/ingress.yml > k8s/ingress-standup.yml
  - envsubst < k8s/deployment.yml > k8s/deployment-standup.yml
  - envsubst < k8s/service.yml > k8s/service-standup.yml
  - envsubst < k8s/certificate.yml > k8s/certificate-standup.yml
  script:
  - kubectl apply -f k8s/certificate-standup.yml -n standup-feature
  - kubectl apply -f k8s/deployment-standup.yml -n standup-feature
  - kubectl apply -f k8s/service-standup.yml -n standup-feature
  - kubectl apply -f k8s/ingress-standup.yml -n standup-feature

.deploy-standup-k8s-master:
  <<: *deploy_stand_up
  before_script:
  - envsubst < k8s/certificate-master.yml > k8s/certificate-standup.yml
  - envsubst < k8s/ingress-master.yml > k8s/ingress-standup.yml
  - envsubst < k8s/deployment.yml > k8s/deployment-standup.yml
  - envsubst < k8s/service.yml > k8s/service-standup.yml
  script:
  - kubectl apply -f k8s/certificate-standup.yml -n standup-master
  - kubectl apply -f k8s/deployment-standup.yml -n standup-master
  - kubectl apply -f k8s/service-standup.yml -n standup-master
  - kubectl apply -f k8s/ingress-standup.yml -n standup-master


