#

Deploy Standup (feature):
  stage: "Deploy Standup"
  <<: *deploy_stage
  variables:
    <<: *deploy_stage_variables
    PORT: ${FRONT_PORT}
    NAMESPACE: ${FEATURE_ENVIRONMENT_NAME}
    LETSENCRYPT_ISSUER: letsencrypt-staging
    IMAGE_TAG: ${CI_COMMIT_SHA}
  environment:
    name: ${FEATURE_ENVIRONMENT_NAME}-${CLUSTER_NAME}
    url: https://${INGRESS_ENVIRONMENT_PREFIX}${APP_NAME}.${DOMAIN_NAME}
  before_script:
    - HASH_BRANCH_NAME=$(printf "${CI_COMMIT_REF_NAME}" | sha1sum | cut -c1-5)
    - export INGRESS_ENVIRONMENT_PREFIX=${HASH_BRANCH_NAME}. # "." at the end of line is needed to deploy into hors prod environment
    - export HELM_RELEASE_NAME=${APP_NAME}-${HASH_BRANCH_NAME}-${FEATURE_ENVIRONMENT_NAME}
    - export HASH_BRANCH_NAME=-${HASH_BRANCH_NAME}
  except:
    - master
    - /^v.*/

Deploy Standup (master):
  stage: "Deploy Standup"
  <<: *deploy_stage
  variables:
    <<: *deploy_stage_variables
    PORT: ${FRONT_PORT}
    NAMESPACE: ${MASTER_ENVIRONMENT_NAME}
    HASH_BRANCH_NAME: ''
    INGRESS_ENVIRONMENT_PREFIX: ${MASTER_ENVIRONMENT_NAME}. # "." at the end of line is needed to deploy into hors prod environment
    LETSENCRYPT_ISSUER: letsencrypt-prod
    IMAGE_TAG: ${CI_COMMIT_SHA}
  environment:
    name: ${MASTER_ENVIRONMENT_NAME}-${CLUSTER_NAME}
    url: https://${MASTER_ENVIRONMENT_NAME}.${APP_NAME}.${DOMAIN_NAME}
  before_script:
    - export HELM_RELEASE_NAME=${APP_NAME}-${MASTER_ENVIRONMENT_NAME}
  only:
    - master

Deploy Standup (preprod):
  stage: "Deploy Standup"
  <<: *deploy_stage
  variables:
    <<: *deploy_stage_variables
    NAMESPACE: ${PREPROD_ENVIRONMENT_NAME}
    HASH_BRANCH_NAME: ''
    INGRESS_ENVIRONMENT_PREFIX: ${PREPROD_ENVIRONMENT_NAME}. # "." at the end of line is needed to deploy into hors prod environment
    LETSENCRYPT_ISSUER: letsencrypt-prod
    IMAGE_TAG: ${RELEASE_VERSION}
  environment:
    name: ${PREPROD_ENVIRONMENT_NAME}-${CLUSTER_NAME}
    url: https://${PREPROD_ENVIRONMENT_NAME}.${APP_NAME}.${DOMAIN_NAME}
  before_script:
    - export HELM_RELEASE_NAME=${APP_NAME}-${PREPROD_ENVIRONMENT_NAME}
  only:
    - /^v.*/


Deploy Standup (prod) :
  stage: "Deploy Standup to prod"
  <<: *deploy_stage
  variables:
    <<: *deploy_stage_variables
    NAMESPACE: ${PROD_ENVIRONMENT_NAME}
    INGRESS_ENVIRONMENT_PREFIX: ''
    LETSENCRYPT_ISSUER: letsencrypt-prod
    IMAGE_TAG: ${RELEASE_VERSION}
  environment:
    name: ${PROD_ENVIRONMENT_NAME}
    url: https://${APP_NAME}.${DOMAIN_NAME}
  before_script:
    - export HELM_RELEASE_NAME=${APP_NAME}-${PROD_ENVIRONMENT_NAME}
  when: manual
  only:
    - /^v.*/
