#

.notify_stage: &notify_stage
  image: ${CI_REGISTRY}/socialgouv/docker/git-deploy:0.2.3
  dependencies: []
  before_script:
    - source .gitlab-ci/env.sh

#

Notify Starting Deployment:
  <<: *notify_stage
  stage: "Deploy Standup"
  script:
    - create-deployment
    - extract-deploy-id
  artifacts:
    paths:
      - DEPLOY_ID

#

Notify Fail:
  <<: *notify_stage
  stage: "Notify Finished Deployment"
  allow_failure: true
  when: on_failure
  dependencies:
    - Notify Starting Deployment
  script:
    - echo "Notify Failure to GitHub deployment id '$(cat $DEPLOY_ID)'"
    - update-deployment $(cat DEPLOY_ID) "${FRONTEND_HOST}" failure

