#

.quality_stage: &quality_stage
  stage: "Code Quality"
  dependencies:
    - Build Assets

#


Test:
  <<: *quality_stage
  extends: .base_node_stage
  script:
    - yarn test

Lint:
  <<: *quality_stage
  extends: .base_node_stage
  script:
    - yarn lint

#

Test Docker image:
  stage: "Test Docker Image"
  except:
    - tags
  image: ${CI_REGISTRY}/${IMAGE_INFRA_BASE_NAME}/curl:${INFRA_CURL_VERSION}
  services:
    - name: ${CI_REGISTRY_IMAGE}:${CI_COMMIT_SHA}
  script:
    - curl -v http://localhost:80
