#

.quality_stage: &quality_stage
  stage: "Code Quality"
  dependencies:
    - Build Assets

#


Test:
  <<: *quality_stage
  extends: .base_node_stage
  script:
    - yarn test

Lint:
  <<: *quality_stage
  extends: .base_node_stage
  script:
    - yarn lint

#

.test_docker_image: &test_docker_image_stage
  stage: "Test Docker Image"
  image: ${CI_REGISTRY}/${IMAGE_INFRA_BASE_NAME}/curl:${INFRA_CURL_VERSION}
  services:
    - name: ${CI_REGISTRY_IMAGE}:${CI_COMMIT_SHA}
  script:
    - curl -v http://localhost:${FRONT_PORT}

Test Docker image:
  <<: *test_docker_image_stage
  except:
    - /^v.*/

Test Docker image tagged with release version:
  <<: *test_docker_image_stage
  only:
    - /^v.*/
