#

.register_stage: &register_stage
  stage: "Register"
  dependencies:
    - Build Assets

#

Register socialgouv/standup:
  <<: *register_stage
  extends: .base_register_to_gitlab_stage
  variables:
    CONTEXT: .
    IMAGE_NAME: ${CI_REGISTRY_IMAGE}
