#

Make a new release to deploy to preprod environment:
  stage: "Make a new release"
  image: ${CI_REGISTRY}/${IMAGE_INFRA_BASE_NAME}/curl:${INFRA_CURL_VERSION}
  script:
    - >-
      curl --verbose POST
      https://${GITHUB_TOKEN}@api.github.com/repos/SocialGouv/standup/git/refs
      --header 'Content-Type:application/json'
      --data '{"ref": "refs/tags/'${RELEASE_VERSION}'", "sha": "'${CI_COMMIT_SHA}'"}'
  when: manual
  only:
    - master
